### ISSUE TITLE
Future and beyond

### ISSUE THREAD

**Issue by brodock** [timimahoney/decaf#15]
Hi, first of all, thanks for this awesome work. If there is anything that can take javascript down, it will have to run on the browser first.

Because of that, I would like to ask you if you plan on update decaf to recent webkit (or maybe Blink) and recent ruby version.

It's a shame that very few people know about this project. It's something that should definitely be on spotlight. You rock!

**Comment by rex** [comment]
@brodock I am one of those very few people. I only just discovered this library about 3 minutes ago. I was gleeful and excited.

But then I saw the age of the commits. 

I am saddened to say that this project is pretty well and truly dead, with nearly a year since the last commit on any branch. :(

Real fucking bummer, too. This looks incredibly fun and useful.

**Comment by timimahoney** [comment]
I loved using Ruby instead of JavaScript, and I hope that we'll soon be able to use other languages in the browser. However, Decaf is dead.

**Comment by rex** [comment]
May it rest in peace. Absolutely fantastic work, @timahoney. Thank you!
