### ISSUE TITLE
ObjectSpace.each_object

### ISSUE THREAD

**Issue by senthilnayagam** [timimahoney/decaf#4]
I am happy with decaf, though not much document, I tried exploring it

 ObjectSpace.each_object does not work, I wanted to know if it has been intentionally left out or we can expect it in future

**Comment by timimahoney** [comment]
Since all the pages currently run in the same VM, `ObjectSpace` would be able to access objects from the other pages. This is insecure, so the `each_object` method is currently disabled. Using multiple processes might solve this, but it'll be disabled for now. The unsafe classes and methods are undefined in [Source/WebCore/bindings/rb/RBSecurityMeasures.cpp](https://github.com/timahoney/decaf/blob/decaf/Source/WebCore/bindings/rb/RBSecurityMeasures.cpp). 

As for documentation, the Ruby API is essentially the same as the [JavaScript DOM API](https://developer.mozilla.org/en-US/docs/Gecko_DOM_Reference). I'll put up some references soon.
